name: Setup Python and Dependencies
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v8.2.0
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync --frozen
      shell: bash
